test release v0.0.6

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -51,9 +51,24 @@ jobs:
           sudo apt update
           sudo apt install gh
 
+      - name: Get commit version
+        id: get_commit_version
+        run: echo ::set-output name=COMMIT_MSG::$(git log -1 --pretty=format:%s)
+
+      - name: Extract version from commit message
+        id: extract_version
+        run: |
+          VERSION_REGEX="^v[0-9]+\.[0-9]+\.[0-9]+$"
+          if [[ ${{ steps.get_last_commit_message.outputs.COMMIT_MSG }} =~ $VERSION_REGEX ]]; then
+            echo ::set-output name=VERSION::${{ steps.get_last_commit_message.outputs.COMMIT_MSG }}
+          else
+            echo "Invalid commit message format. Skipping release creation."
+            exit 1
+          fi    
+
       - name: Create or Get Release
         id: create_release
-        run: gh release create ${{ github.ref }} --title "Release ${{ github.ref }}" --notes "Release ${{ github.ref }}" --draft=false --prerelease=false
+        run: gh release create ${{ steps.extract_version.outputs.VERSION }} --title "Release ${{ steps.extract_version.outputs.VERSION }}" --notes "Release ${{ steps.extract_version.outputs.VERSION }}" --draft=false --prerelease=false
         env:
           GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
 
